version: "3.5"

networks:
  glos-app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    networks:
      - glos-app-network
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: kVDeESM2vHeIxCT7
      MYSQL_DATABASE: glos_database
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  minio:
    image: minio/minio:latest
    container_name: minio
    networks:
      - glos-app-network
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server ~/minio --console-address :9097
    ports:
      - '9097:9097'
      - '9000:9000'
    volumes:
      - ./minio-data:/minio
